qa/urls.py
from django.conf.urls import url,include
from .views import QuestionDetail,AnswerDetail,QACenterView
from . import views

app_name='qa'
urlpatterns=[
    url('^$',QACenterView.as_view(),name='qa_center'),
    url('^ask/$',views.ask,name='ask'),
    url('^answer/$',views.answer,name='answer'),
    url('^Q_detail/(?P<pk>\d{1,5})/$',QuestionDetail.as_view(),name='question_detail'),
    url('^A_detail/(?P<pk>\d{1,5})/$',AnswerDetail.as_view(),name='answer_detail')
]

user/urls.py
from django.conf.urls import url,include
from user import views

app_name='user'
urlpatterns=[
    url(r'^$',views.auth,name='auth'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^signin/$',views.signin,name='signin'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^find_passwd/$',views.find_passwd,name='find_passwd'),
    url(r'^user_info/(?P<user_id>\d{1,5})/$',views.user_info,name='user_info'),
    url(r'^personal_info/$',views.personal_info,name='personal_info')
]

usst_info/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from search import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^search/',include('search.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^qa/',include('qa.urls')),
]

qa/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models
from user.models import Userinfo
from django.urls import reverse

class Question(models.Model):
    """
    问题表，所有属性默认非空

    asker：提问者， 外键，严格约束
    title：问题标题
    content：问题内容
    pubtime：发布时间，默认为当前时间
    categories：问题所属类别，可选多类，存为json字符串
    glances:问题在搜索结果页被点击的次数，默认为0
    if_delete：该回答是否被删除，默认为0,删除后不显示给用户
    """
    asker = models.ForeignKey(Userinfo,on_delete=models.PROTECT)
    title = models.CharField(max_length=200)
    content = models.CharField(max_length=10000)
    pubtime = models.DateTimeField(auto_now=True,blank=True)
    categories = models.TextField()
    glances=models.IntegerField(default=0)
    if_delete = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('qa:question_detail',kwargs={'pk':self.pk})

    class Meta:
        db_table = 'question'


class Answer(models.Model):
    """
    回答表，所有属性默认非空

    question：对应问题的id,外键,保证完整性
    answer：回答者的id，外键，严格约束
    content：回答内容，不超过10000个字符
    pubtime：提交时间，默认为当前时间
    glances:答案在搜索结果页被点击的次数，默认为0
    if_read：该回答是否已经被问题发布者读过，默认为0
    if_delete：该回答是否被删除，默认为0,删除后不显示给用户

    """
    question = models.ForeignKey(Question,on_delete=models.PROTECT)
    answerer = models.ForeignKey(Userinfo,on_delete=models.PROTECT)
    content = models.CharField(max_length=10000)
    pubtime = models.DateTimeField(auto_now=True)
    glances=models.IntegerField(default=0)
    if_read = models.IntegerField(default=0)
    if_delete = models.IntegerField(default=0)

    class Meta:
        db_table = 'answer'

    def __str__(self):
        return self.question+self.content

class Comment(models.Model):
    """
    评论表，所有属性默认非空

    answer：所属答案id,外键，因为答案不可删，只是防止直接操作数据库删除，
            所以严格控制外键约束
    replier：评论者或者回复者id，外键，严格约束
    reply_to：回复对象id，评论时为评论发布者 ，当为回复时，表示目标对象，外键，严格约束
    content：回复内容
    pubtime：提交时间，默认为当前时间
    reply_in：当为回复时，允许为空，表示回复所属的评论
    if_read：是否被目标对象（当为评论时即为答案发布者）阅读过，默认为0
    if_delete：是否删除，默认为0,删除后不显示给用户

    """
    answer = models.ForeignKey(Answer,on_delete=models.PROTECT)
    replier = models.ForeignKey(Userinfo,on_delete=models.PROTECT,related_name='start_reply')
    reply_to = models.ForeignKey(Userinfo,on_delete=models.PROTECT,related_name='accept_reply')
    content = models.CharField(max_length=2000)
    pubtime = models.DateTimeField(auto_now=True)
    if_reply = models.IntegerField(default=0)
    reply_in = models.ForeignKey('self',on_delete=models.PROTECT,blank=True,null=True)
    if_read = models.IntegerField(default=0)
    if_delete = models.IntegerField(default=0)

    class Meta:
        db_table = 'comment'


class Invitation(models.Model):
    """
        邀请表，所有属性默认非空

        invited：邀请回答用户id，外键，严格约束
        question：问题id,外键，因为不可删，只是防止直接操作数据库删除，
                 所以严格控制外键约束
        state：邀请信息状态，未处理为0，已答为1，忽略为2，默认0
        content：邀请内容
        pubtime：提交时间，默认为当前时间
        if_delete：是否删除，默认为0,删除后不显示给用户

    """
    invited= models.ForeignKey(Userinfo,on_delete=models.PROTECT)
    question = models.ForeignKey(Question,on_delete=models.PROTECT)
    state = models.IntegerField(default=0)
    content=models.CharField(max_length=100)
    pubtime = models.DateTimeField(auto_now=True)
    if_delete = models.IntegerField(default=0)

    class Meta:
        db_table = 'invitation'


class Updown(models.Model):
    """
        点赞表，所有属性默认非空

        id：主键
        if_up：是否为点赞，0踩，1为点赞
        if_down：是否为回答，0为评论，1是
        ac_id：回答或评论的id，由于不确定类型，所以不能设置外键，由程序实现
        user：点赞用户的id，外键严格约束

    """
    id = models.BigIntegerField(primary_key=True)
    if_up = models.IntegerField()
    if_ans = models.IntegerField()
    ac_id = models.IntegerField()
    user = models.ForeignKey(Userinfo,on_delete=models.PROTECT)

    class Meta:
        db_table = 'updown'

qa/views.py
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from django.views.decorators.csrf import csrf_protect, csrf_exempt

from .models import Question,Answer
from django.views.generic import ListView,DetailView
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from user.models import Userinfo
from django.contrib.auth import SESSION_KEY
import json

class QACenterView(ListView):
    model=Question

    template_name = "qa/qa_center.html"

    def get_context_data(self,**kwargs):
        context=super().get_context_data(**kwargs)
        return context

def ask(request):
    title=request.POST['title']
    content=request.POST['content']
    categories=request.POST['categories']
    asker=request.session.get(SESSION_KEY)
    question=Question.objects.create(title=title,content=content,categories=categories,asker_id=asker)
    return HttpResponseRedirect('/qa/Q_detail/'+str(question.id)+'/')

def answer(request):
    """
    对问题的回答

    :param request:
    :return:
    """
    content=request.POST['content']
    # question_id=request.GET['question_id']
    question_id=26
    answerer=request.session.get(SESSION_KEY)
    answer=Answer.objects.create(question_id=question_id,content=content,answerer_id=answerer)
    return HttpResponseRedirect('/qa/A_detail/'+str(answer.pk)+'/')

class QuestionDetail(DetailView):
    """
    继承自DetailView，提供get_object函数（自动寻找并利用请求的url中携带的pk或slug参数，
    得到对应的模型对象），并默认寻求'<modelname>_detail.html'模板
    """
    model=Question

    def get_context_data(self, **kwargs):
        context=super(QuestionDetail,self).get_context_data(**kwargs)
        question=self.get_object()
        context['user']=question.asker
        return context

class AnswerDetail(DetailView):
    """
    继承自DetailView，提供get_object函数（自动寻找并利用请求的url中携带的pk或slug参数，
    得到对应的模型对象），并默认寻求'<modelname>_detail.html'模板
    """
    model=Answer

    def get_context_data(self, **kwargs):
        context=super(AnswerDetail,self).get_context_data(**kwargs)
        answer=self.get_object()
        context['user']=answer.answerer
        return context

templates/qa/answer.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% include "components/head.html" %}
  <link rel="stylesheet" href="/static/css/ask.css">
</head>
<body>
答案
</body>
</html>

templates/qa/answer_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ object.answerer }}
{{ object.content }}
</body>
</html>

templates/qa/ask.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% include "components/head.html" %}
  <link rel="stylesheet" href="/static/css/ask.css">
</head>
<body>
  {% include "components/nav_search_form.html" %}
  <div class="main">
    <div class="container content">
      <div class="row">
        <div class="col-xs-10 col-sm-10 col-md-8">
          <form method="post">
            {% csrf_token %}
            <div class="form-group">
              <p>问题名：{{ form.title }}</p>
            </div>
            <div class="form-group">
              <p>问题描述： {{ form.content }}</p>
            </div>
            <div class="form-group">
              <p>问题分类：{{ form.categories }}</p>
            </div>
            <div class="form-group">
              <input type="submit" name="" value="提交">
              <input type="button" name="" value="返回">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  {% include "components/footer.html" %}
</body>
</html>

templates/qa/qa_center.html
<!DOCTYPE html>
<html lang="en">
{% load my_filters %}
<head>
  {% include "components/head.html" %}
    <title>问答中心</title>
  <link rel="stylesheet" href="/static/css/result.css">
</head>
<body>
<div class="main">
  {% include "components/nav_search_form.html" %}
  <!--搜索问答结果展示模块-->
  <ul>
  {% for object in object_list %}
      <li>会被挡住啊</li>
      {% if object|isinst:'qa.models.Question' %}
        <li><a href="/qa/Q_detail/{{ object.pk}}">{{ object.title }}</a></li>
      {% else %}
        <li><a href="/qa/A_detail/{{ object.pk }}">{{ object.question }}</a></li>
      {% endif %}
  {% endfor %}
  </ul>
</body>
</html>

templates/qa/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% include "components/head.html" %}
  <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
  <link rel="stylesheet" href="/static/css/question_detail.css">
  <link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <script src="http://libs.baidu.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
</head>
<script>
{#$(document).ready(function() {#}
{#    $("#test").click(function () {#}
{#        $.ajax({#}
{#            url:"/qa/answer/",#}
{#            data:{'question':26},#}
{#            type:'post',#}
{#            success:function(result){#}
{#                alert('ok');#}
{#            }#}
{#        });#}
        {#$.post("/qa/answer/",#}
        {#    {#}
        {#        content: $("#content").val(),#}
        {#        question: 26,#}
        {#    },#}
        {#    function (data, status) {#}
        {#        alert(data.q);#}
        {#    });#}
{#    });#}
{# });#}
</script>
<body>
  {% include "components/nav_search_form.html" %}
  <div class="main">
    <div class="content">
      <div class="left">
        <div class="question">
          <p>提问者：<a href="{% url 'user:user_info' user.id %}">{{ user.username }}</a></p>
          <p>问题标题：{{ object.title }}</p>
          <p>问题描述：{{ object.content }}</p>
          <p>问题标签：{{ object.categories }}</p>
          <p>提问时间：{{ object.pubtime }}</p>
        </div>
      </div>
      <div>
          <button class="btn btn-primary btn-sm" data-toggle="modal"  data-target="#answer">
              回答
          </button>
      </div>
    </div>
      <div class="right">
        <!-- 推荐区？ -->
      </div>
    </div>

<form method="post" action="{% url 'qa:answer' %}" class="form-horizontal" role="form" id="form_data" style="margin: 20px;">
    <div class="modal fade" id="answer" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        回答
                    </h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label for="remark" class="col-sm-3 control-label">回答</label>
                            <div class="col-sm-9">
                                <textarea  class="form-control"  name="content"  id="content"
                                       placeholder="content">
                                </textarea>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                    </button>
                    <button type="submit" class="btn btn-primary">
                        提交
                    </button>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>
    </form>
  {% include "components/footer.html" %}
</body>
</html>