qa/urls.py
from django.conf.urls import url,include
from .views import QuestionDetail,AnswerDetail,QACenterView
from . import views

app_name='qa'
urlpatterns=[
    url('^$',QACenterView.as_view(),name='qa_center'),
    url('^ask/$',views.ask,name='ask'),
    url('^answer/$',views.answer,name='answer'),
    url('^Q_detail/(?P<pk>\d{1,5})/$',QuestionDetail.as_view(),name='question_detail'),
    url('^A_detail/(?P<pk>\d{1,5})/$',AnswerDetail.as_view(),name='answer_detail')
]

search/urls.py
from django.conf.urls import url,include
from search import views
from search import search_views

app_name='search'
urlpatterns=[
    url(r'^$',search_views.MySearchView(),name='haystack_search')
]

usst_info/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from search import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^search/',include('search.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^qa/',include('qa.urls')),
]

search/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Jwcinfo(models.Model):
    """
       爬取的学校公共信息表，所有属性默认非空

       title：标题，允许为空
       body：正文，允许为空
       url：所属通知链接，允许为空
       glances：通知在本网站被点击浏览的次数，默认为0
       crawltime：爬取时间，默认当前时间
       download：是否包含下载，默认为0，不包含
       site：通知来源网站
       pubtime：通知在来源网站的发布时间，允许为空
    """
    title = models.CharField(max_length=200, blank=True, null=True)
    body = models.TextField(blank=True, null=True)
    url = models.CharField(unique=True, max_length=200, blank=True, null=True)
    glances = models.IntegerField(default=0)
    crawltime = models.DateTimeField(auto_now=True)
    download = models.IntegerField(default=0)
    site = models.CharField(max_length=20)
    pubtime = models.DateField(blank=True, null=True)

    class Meta:
        db_table = 'jwcinfo'


class PersonalInfo(models.Model):
    """
       爬取的用户在学校的个人信息表，所有属性默认非空

       st：学生的学号，为了方便，没有使用学生表对应的id，所以需要有程序保证引用完整性，唯一
       info：学生信息的json字符串
       crawltime：爬取时间，默认为爬取的当前时间
    """
    st = models.CharField(max_length=10,unique=True)
    info = models.TextField()
    crawltime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'personal_info'

search/views.py
# -*- encoding:utf-8 -*-
from django.shortcuts import render
from django.contrib.auth import SESSION_KEY
from user.models import Userinfo
# Create your views here.


def index(request):
    """
    网站的首页，无需登录即可进入，可以搜索、登录、注册、进入用户中心、查看推荐信息等

    :param request:
    :return:
    """
    user=None
    if request.session.get(SESSION_KEY,None):
        user=Userinfo.objects.get(pk=request.session.get(SESSION_KEY))
    if user:
        info={'url':'/user/personal_info','name':user.username}
    else:
        info={'url':'/user','name':'登录/注册'}
    return render(request,'index.html',info)

templates/search/search.html
<!DOCTYPE html>
{% load highlight %}
<html lang="en">
<head>
  {% include "components/head.html" %}
  <link rel="stylesheet" href="/static/css/result.css">
</head>
<body>
<div class="main">
  {% include "components/nav_search_form.html" %}
  <!--搜索结果展示模块-->
  <section class="result">
    {% if query %}
    {% for result in page.object_list %}
      <!--搜索结果为问题的格式-->
      {% if result.asker %}
          <div class="oneofresults">
      <div class="result-head">
        <a href="{% url 'qa:question_detail' result.pk %}" >{{result.title}} - 问</a>
      </div>
      <div class="result-body">
        <p>{% highlight result.text with query css_class "keyword" %}</p>
      </div>
      <div class="result-footer">
        <span>{{ result.pubtime }}&nbsp;</span>
        <span>浏览：{{ result.glances }}</span>
      </div>
      </div>
       <!--搜索结果为答案的格式-->
      {% elif result.answerer %}
          <div class="oneofresults">
      <div class="result-head">
      <a href="{% url 'qa:answer_detail' result.pk %}">{{ result.question }} - 答</a>
      </div>
      <div class="result-body">
        <p>{% highlight result.text with query css_class "keyword" %}</p>
      </div>
      <div class="result-footer">
        <span>{{ result.pubtime }}&nbsp;</span>
        <span>浏览：{{ result.glances }}</span>
      </div>
      </div>
          <!--搜索结果为通知的格式-->
      {% elif result.site %}
      <div class="oneofresults">
      <div class="result-head">
        <a href="{{ result.url }}" id="{{ result.id }}">{{ result.title }} - 通知</a>
      </div>
      <div class="result-body">
        <p>{% highlight result.text with query css_class "keyword" %}</p>
      </div>
      <div class="result-footer">
        {% if result.download == 1 %}
        <span>含下载&nbsp;</span>
        {% endif %}
        <span>{{ result.site }}&nbsp;</span>
        <span>{{ result.pubtime }}&nbsp;</span>
        <span>浏览：{{ result.glances }}</span>
      </div>
      </div>
      {% endif %}
    {% empty %}

    <p>没有结果发现</p>
    {% endfor %}
    {% endif %}

    <!-- 分页模块 -->
    {% if page.has_previous or page.has_next %}
    <section class="center">
      {% if page.has_previous %}
      <a href="?q={{ query }}&page={{ page.previous_page_number }}">上一页</a>
      {% endif %}
      <select>
        {% for i in paginator.page_range %}
        <option value="{{ i }}">{{ i }}</option>
        {% endfor %}
      </select>
      {% if page.has_next %}
      <a href="?q={{ query }}&page={{ page.next_page_number }}">下一页</a>
      {% endif %}
    </section>
    {% endif %}
  </section>
  <!--推荐模块-->
  <aside class="commend">

  </aside>
</div>


  <!-- 页脚 -->
  {% include "components/footer.html" %}
</body>
</html>