qa/urls.py
from django.conf.urls import url,include
from .views import QuestionDetail,AnswerDetail,QACenterView
from . import views

app_name='qa'
urlpatterns=[
    url('^$',QACenterView.as_view(),name='qa_center'),
    url('^ask/$',views.ask,name='ask'),
    url('^answer/$',views.answer,name='answer'),
    url('^Q_detail/(?P<pk>\d{1,5})/$',QuestionDetail.as_view(),name='question_detail'),
    url('^A_detail/(?P<pk>\d{1,5})/$',AnswerDetail.as_view(),name='answer_detail')
]

usst_info/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from search import views

urlpatterns = [
    url(r'^$', views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^search/',include('search.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^qa/',include('qa.urls')),
]

templates/components/footer.html
<footer>
  <hr>
  <p class="center">&copy;Jelly 2017</p>
</footer>

templates/components/head.html
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <title>Jelly</title>
  <link rel="shortcut icon" href="/static/images/favicon.ico">
  <script src="http://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
  <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" rel="stylesheet">
  <link rel="stylesheet" href="/static/css/base.css">

templates/components/nav_qa.html
<!--问答中心导航栏，带搜索表单-->
{% load my_filters %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#user_items').hide()
        $('#user').mouseover(function() {
            if($("#user").children('a').text()!="登录/注册"){
                $("#user_items").show();
            }
        });
        $('#user').mouseleave(function(){
            $("#user_items").hide();
        })
    });
    function search_qa() {
        document.form1.action = "/qa/search";
        document.form1.submit();
    }
</script>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!--头部Jelly标识-->
    <div class="navbar-header">
      <!--小屏设备（width<768px）隐藏登录标签以及个人信息-->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#user_info">
        <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>
      </button>
      <a href="/" class="navbar-brand">Jelly</a>
    </div>
    <form name="form1" class="navbar-form pull-left form-in-nav" method="get">
      <input type="search" id="q" name="q" class="search-in">
      <input id="jelly_search_btn" type="button" value="搜问答" onclick="search()">
    </form>
    <!--登录标签以及个人信息-->
    <div class="collapse navbar-collapse" id="user_info">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/qa/">QA</a></li>
        <li><a href="{{ url }}" id="user">{{ name }}</a>
          <ul id="user_items" class="dropdown-menu dropdown-menu-right">
          <li><a href="/user/user_info/{{ request.session | get_attr:'_auth_user_id'}}">个人资料</a></li>
              <li><a href="/user/logout">退出</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/components/nav_search.html
<!--导航栏-->
{% include "components/head.html" %}
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<link href="http://libs.baidu.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    $(document).ready(function(){
        $('#user_items').hide()
        $('#user').mouseover(function() {
            if($("#user").children('a').text()!="登录/注册"){
                $("#user_items").show();
            }
        });
        $('#user').mouseleave(function(){
            $("#user_items").hide();
        })
    });
</script>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!--头部Jelly标识-->
    <div class="navbar-header">
      <!--小屏设备（width<768px）隐藏登录标签以及个人信息-->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#user_info">
        <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>
      </button>
      <a href="/" class="navbar-brand">Jelly</a>
    </div>
    <!--登录标签以及个人信息-->
    <div class="collapse navbar-collapse" id="user_info">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/qa/">QA</a></li>
        <li id='user'><a href="{{ url }}">{{ name }}</a>
          <ul id="user_items" class="dropdown-menu dropdown-menu-right">
          {% load my_filters %}
          <li><a href="/user/user_info/{{ request.session | get_attr:'_auth_user_id'}}/">个人资料</a></li>
              <li><a href="/user/logout">退出</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/components/nav_search_form.html
<!--导航栏，带搜索表单-->
{% load my_filters %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#user_items').hide()
        $('#user').mouseover(function() {
            if($("#user").children('a').text()!="登录/注册"){
                $("#user_items").show();
            }
        });
        $('#user').mouseleave(function(){
            $("#user_items").hide();
        })
    });
    function search(){
        document.form1.action="/search";
        document.form1.submit();
    }
    function ask(){
        var current_user=$('#current_user').text();
        if(current_user!='登录/注册'){
            $('#ask').modal({
                show: 'true'
            });
        }else{
            alert('请您先登录！');
        }
    }
</script>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!--头部Jelly标识-->
    <div class="navbar-header">
      <!--小屏设备（width<768px）隐藏登录标签以及个人信息-->
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#user_info">
        <span class="glyphicon glyphicon-align-justify" aria-hidden="true"></span>
      </button>
      <a href="/" class="navbar-brand">Jelly</a>
    </div>
    <form name="form1" class="navbar-form pull-left form-in-nav" method="get">
      <input type="search" id="q" name="q" class="search-in">
      <input id="jelly_search_btn" type="button" value="搜索" onclick="search()">
      <input id="jelly_ask_btn" type="button" value="提问" onclick="ask()">
    </form>
    <!--登录标签以及个人信息-->
    <div class="collapse navbar-collapse" id="user_info">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/qa/">QA</a></li>
        <li><a href="{{ url }}" id="user">{{ name }}</a>
          <ul id="user_items" class="dropdown-menu dropdown-menu-right">
          <li><a href="/user/user_info/{{ request.session | get_attr:'_auth_user_id'}}">个人资料</a></li>
              <li><a href="/user/logout">退出</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<form method="post" action="{% url 'qa:ask' %}" class="form-horizontal" role="form" id="form_data" style="margin: 20px;">
    <div class="modal fade" id="ask" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                        &times;
                    </button>
                    <h4 class="modal-title" id="myModalLabel">
                        提问
                    </h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" role="form">
                        <div class="form-group">
                            <label for="title" class="col-sm-3 control-label">标题</label>
                            <div class="col-sm-9" id="title">
                                <textarea  class="form-control"  name="title"  id="title"
                                       placeholder="标题">
                                </textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="content" class="col-sm-3 control-label">内容</label>
                            <div class="col-sm-9" id="content">
                                <textarea  class="form-control"  name="content"  id="content"
                                       placeholder="内容">
                                </textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="categories" class="col-sm-3 control-label">标签</label>
                            <div class="col-sm-9" id="categories">
                                <textarea  class="form-control"  name="categories" id="categories"
                                       placeholder="标签">
                                </textarea>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">关闭
                    </button>
                    <button type="submit" class="btn btn-primary">
                        提交
                    </button><span id="tip"> </span>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal -->
    </div>
    </form>